// pages/new.vue
<template>
  <div class="content">
    <NuxtLink to="/dashboard">
      <SchoolLogo size="100" />
    </NuxtLink>
    <h1>Stwórz zebranie</h1>
    <Card>
      <div class="card-content">
        <h3>Data zebrania</h3>
        <input type="date" v-model="date" />
        <h3>Godzina</h3>
        <div>
          <input type="time" v-model="start" />
          <input type="time" v-model="end" />
        </div>
        <h3>Nauczyciele</h3>
        <div class="teacher">
          Joanna Rzeźniowiecka
          <input type="checkbox" />
        </div>
        <div class="teacher">
          Alice Wstała
          <input type="checkbox" />
        </div>
        <div class="teacher">
          Jarosław Drzemdżon
          <input type="checkbox" />
        </div>
      </div>
    </Card>
    <button @click="addMeeting()">Dodaj</button>
  </div>
</template>

<script lang="ts">
export default {
  head: {
    title: "Dodaj zebranie",
  },
  setup() {
    const date = ref(new Date().toISOString().substring(0, 10));
    const start = ref(new Date().toISOString().substring(11, 16));
    const end = ref(new Date().toISOString().substring(11, 16));

    const addMeeting = () => {
      const [startHours, startMinutes] = start.value.split(':').map(e => parseInt(e));
      const [endHours, endMinutes] = end.value.split(':').map(e => parseInt(e));
      const startsAt = new Date(date.value);
      const endsAt = new Date(date.value);

      startsAt.setHours(startHours, startMinutes);
      endsAt.setHours(endHours, endMinutes);

      console.log(startsAt);
      console.log(endsAt);
    };

    return {
      start,
      end,
      date,
      addMeeting,
    };
  },
};
</script>

<style lang="less" scoped>
@import "@/assets/colors.less";

h1 {
  font-weight: 800;
  font-size: 36px;
  color: @text;
}

input[type="checkbox"] {
  appearance: none;
  -moz-appearance: none;
  -webkit-appearance: none;
  margin: 3px;
  width: 24px;
  height: 24px;
  border: 0;
  background: #c4c4c4;
  border-radius: 100%;
  &:checked {
    background: darken(@tertiary, 30%);
    background-image: url("data:image/svg+xml;base64,PCEtLSBHZW5lcmF0ZWQgYnkgSWNvTW9vbi5pbyAtLT4KPHN2ZyB2ZXJzaW9uPSIxLjEiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgd2lkdGg9IjQ0OCIgaGVpZ2h0PSI0NDgiIHZpZXdCb3g9IjAgMCA0NDggNDQ4Ij4KPHRpdGxlPjwvdGl0bGU+CjxnIGlkPSJpY29tb29uLWlnbm9yZSI+CjwvZz4KPHBhdGggZD0iTTQxNy43NSAxNDEuNWMwIDYuMjUtMi41IDEyLjUtNyAxN2wtMjE1IDIxNWMtNC41IDQuNS0xMC43NSA3LTE3IDdzLTEyLjUtMi41LTE3LTdsLTEyNC41LTEyNC41Yy00LjUtNC41LTctMTAuNzUtNy0xN3MyLjUtMTIuNSA3LTE3bDM0LTM0YzQuNS00LjUgMTAuNzUtNyAxNy03czEyLjUgMi41IDE3IDdsNzMuNSA3My43NSAxNjQtMTY0LjI1YzQuNS00LjUgMTAuNzUtNyAxNy03czEyLjUgMi41IDE3IDdsMzQgMzRjNC41IDQuNSA3IDEwLjc1IDcgMTd6Ij48L3BhdGg+Cjwvc3ZnPgo=");
    background-repeat: no-repeat;
    background-position: 4px 4px;
    background-size: 16px 16px;
    filter: invert(1) hue-rotate(180deg);
  }
}

input[type="date"],
input[type="time"] {
  user-select: none;
  border: solid 2px #e8e8e8;
  background: #e8e8e8;
  border-radius: 10px;
  padding: 10px;
  height: 30px;
  font-family: 'Poppins', sans-serif;
  font-weight: 700;
  color: @text;
  outline-color: @text;
  // Fix on iOS devices
  -webkit-appearance: textfield;
  -moz-appearance: textfield;
}

input[type="date"] {
  width: calc(100% - 20px);
}

input[type="time"] {
  width: calc(50% - 28px);
  &:first-child {
    margin-right: 4px;
  }
  &:last-child {
    margin-left: 4px;
  }
}

.teacher {
  display: grid;
  grid-template-columns: 1fr 30px;
  border: solid 2px #e8e8e8;
  background: #e8e8e8;
  border-radius: 10px;
  padding: 10px;
  height: 30px;
  font-family: 'Poppins', sans-serif;
  font-weight: 700;
  color: @text;
  line-height: 30px;
  margin: 10px 0;
}

.card-content {
  margin: 0 20px 1.6em 20px;
  text-align: left;
}

.content {
  display: block;
  padding: 36px 0;
  height: calc(100vh - 36px * 2);
  text-align: center;
  overflow-y: auto;
  overflow-x: hidden;
}

button {
  border: 0;
  padding: 0 10px;
  display: inline-block;
  width: calc(100% - 60px);
  max-width: 400px;
  background: @important;
  margin: 10px 20px;
  border-radius: 10px;
  height: 50px;
  color: @text;
  font-size: 20px;
  font-weight: 900;
  line-height: 50px;
  transition: transform 250ms;
  &:hover {
    cursor: pointer;
  }
}
</style>

// pages/dashboard/new.tsx
import Card from '../../components/Card';
import SchoolLogo from '../../components/SchoolLogo';
import Link from 'next/link';
import { useRouter } from 'next/router';
import { useState } from 'react';
import { ConfigTeacherDTO } from '../../server/models/dto/teacher';

export async function getServerSideProps(context) {
	console.log(context.resolvedUrl)
  const res = await fetch('http://localhost:3000/api/teachers');
  const teachers = await res.json();

  return {
    props: {
      teachers,
    },
  }
}

export default function New(props) {
	const router = useRouter();

	const [teachers, setTeachers] = useState<Array<ConfigTeacherDTO & { active: boolean }>>(props.teachers.map((teacher) => ({...teacher, active: true})));

	const [date, setDate] = useState(new Date().toISOString().substring(0, 10));
	const [start, setStart] = useState(new Date().toISOString().substring(11, 16));
	const [end, setEnd] = useState(new Date().toISOString().substring(11, 16));

	const addMeeting = async () => {
		const [startHours, startMinutes] = start
			.split(":")
			.map((e) => parseInt(e));
		const [endHours, endMinutes] = end.split(":").map((e) => parseInt(e));
		const startsAt = new Date(date);
		const endsAt = new Date(date);

		startsAt.setHours(startHours, startMinutes);
		endsAt.setHours(endHours, endMinutes);

		await fetch("/api/admin/meetings", {
			method: "post",
			headers: {
				authorization:
					"adf eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbiI6dHJ1ZSwiaWF0IjoxNjM2MjQzODY2LCJleHAiOjE2MzY0MTY2NjZ9.DDXwuun-RfJOdt22Q5h9skljWL_WeN2vDclxUyefMZg",
				"content-type": "application/json",
			},
			body: JSON.stringify({
				startsAt: startsAt.getTime(),
				endsAt: endsAt.getTime(),
				teacherIds: teachers
					.filter((teacher) => teacher.active)
					.map((teacher) => teacher.id),
			}),
		});

		router.push("/dashboard");
	};

	return (<>
	 <div className="content">
    <Link href="/dashboard" passHref>
      <SchoolLogo />
    </Link>
    <h1>Stwórz zebranie</h1>
    <Card>
      <div className="card-content">
        <h3>Data zebrania</h3>
        <input type="date" value={date} onChange={(e) => setDate(e.target.value)} />
        <h3>Godzina</h3>
        <div>
          <input type="time" value={start} onChange={(e) => setStart(e.target.value)}/>
          <input type="time" value={end} onChange={(e) => setEnd(e.target.value)}/>
        </div>
        <h3>Nauczyciele</h3>
        <div className="teachers">
						{teachers.map((teacher, idx) => <div className="teacher" key={teacher.name}>
							<p>{teacher.name}</p>
      	      <input type="checkbox" checked={teacher.active} onChange={(e) => {
								const newTeachers = [...teachers];
								newTeachers[idx] = {...teachers[idx], active: e.target.checked};
								setTeachers(newTeachers);
							}}/>
						</div>)}
        </div>
      </div>
    </Card>
    <button onClick={addMeeting}>Dodaj</button>
  </div>
	<style jsx>{`
			@import "styles/index.less";

			input[type="time"] {
				width: calc(50% - 28px);
				&:first-child {
					margin-right: 4px;
				}
				&:last-child {
					margin-left: 4px;
				}
			}

			.teachers {
				margin-top: -10px;
				max-height: 190px;
				overflow-x: hidden;
				overflow-y: auto;
			}

			.teacher {
				display: grid;
				grid-template-columns: 1fr 30px;
				border: solid 2px #e8e8e8;
				background: #e8e8e8;
				border-radius: 10px;
				padding: 10px;
				height: 30px;
				font-family: "Poppins", sans-serif;
				font-weight: 700;
				color: @text;
				line-height: 30px;
				margin: 10px 0;
				&:first-child {
					margin-top: 4px;
				}
				&:last-child {
					margin-bottom: 4px;
				}
				p {
					margin: 0;
					white-space: nowrap;
					text-overflow: ellipsis;
					overflow: hidden;
					max-width: 270px;
				}
			}

			.card-content {
				margin: 0 20px 1.6em 20px;
				text-align: left;
			}
		`}
	</style>
	</>);
}
